// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.world
{

using System;
using FlatBuffers;

public struct AppearRemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AppearRemoteCharacter GetRootAsAppearRemoteCharacter(ByteBuffer _bb) { return GetRootAsAppearRemoteCharacter(_bb, new AppearRemoteCharacter()); }
  public static AppearRemoteCharacter GetRootAsAppearRemoteCharacter(ByteBuffer _bb, AppearRemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AppearRemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public RemoteCharacter? Character { get { int o = __p.__offset(4); return o != 0 ? (RemoteCharacter?)(new RemoteCharacter()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<AppearRemoteCharacter> CreateAppearRemoteCharacter(FlatBufferBuilder builder,
      Offset<RemoteCharacter> characterOffset = default(Offset<RemoteCharacter>)) {
    builder.StartObject(1);
    AppearRemoteCharacter.AddCharacter(builder, characterOffset);
    return AppearRemoteCharacter.EndAppearRemoteCharacter(builder);
  }

  public static void StartAppearRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacter(FlatBufferBuilder builder, Offset<RemoteCharacter> characterOffset) { builder.AddOffset(0, characterOffset.Value, 0); }
  public static Offset<AppearRemoteCharacter> EndAppearRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AppearRemoteCharacter>(o);
  }
};


}
