// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.world
{

using System;
using FlatBuffers;

public struct DisappearRemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DisappearRemoteCharacter GetRootAsDisappearRemoteCharacter(ByteBuffer _bb) { return GetRootAsDisappearRemoteCharacter(_bb, new DisappearRemoteCharacter()); }
  public static DisappearRemoteCharacter GetRootAsDisappearRemoteCharacter(ByteBuffer _bb, DisappearRemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DisappearRemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<DisappearRemoteCharacter> CreateDisappearRemoteCharacter(FlatBufferBuilder builder,
      int uuid = 0) {
    builder.StartObject(1);
    DisappearRemoteCharacter.AddUuid(builder, uuid);
    return DisappearRemoteCharacter.EndDisappearRemoteCharacter(builder);
  }

  public static void StartDisappearRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(0, uuid, 0); }
  public static Offset<DisappearRemoteCharacter> EndDisappearRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DisappearRemoteCharacter>(o);
  }
};


}
