// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.world
{

using System;
using FlatBuffers;

public struct DisappearRemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DisappearRemoteCharacter GetRootAsDisappearRemoteCharacter(ByteBuffer _bb) { return GetRootAsDisappearRemoteCharacter(_bb, new DisappearRemoteCharacter()); }
  public static DisappearRemoteCharacter GetRootAsDisappearRemoteCharacter(ByteBuffer _bb, DisappearRemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DisappearRemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUuidBytes() { return __p.__vector_as_arraysegment(4); }

  public static Offset<DisappearRemoteCharacter> CreateDisappearRemoteCharacter(FlatBufferBuilder builder,
      StringOffset uuidOffset = default(StringOffset)) {
    builder.StartObject(1);
    DisappearRemoteCharacter.AddUuid(builder, uuidOffset);
    return DisappearRemoteCharacter.EndDisappearRemoteCharacter(builder);
  }

  public static void StartDisappearRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUuid(FlatBufferBuilder builder, StringOffset uuidOffset) { builder.AddOffset(0, uuidOffset.Value, 0); }
  public static Offset<DisappearRemoteCharacter> EndDisappearRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DisappearRemoteCharacter>(o);
  }
};


}
