// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct HittingInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static HittingInfo GetRootAsHittingInfo(ByteBuffer _bb) { return GetRootAsHittingInfo(_bb, new HittingInfo()); }
  public static HittingInfo GetRootAsHittingInfo(ByteBuffer _bb, HittingInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public HittingInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUuidBytes() { return __p.__vector_as_arraysegment(4); }
  public int Damage { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<HittingInfo> CreateHittingInfo(FlatBufferBuilder builder,
      StringOffset uuidOffset = default(StringOffset),
      int damage = 0) {
    builder.StartObject(2);
    HittingInfo.AddDamage(builder, damage);
    HittingInfo.AddUuid(builder, uuidOffset);
    return HittingInfo.EndHittingInfo(builder);
  }

  public static void StartHittingInfo(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddUuid(FlatBufferBuilder builder, StringOffset uuidOffset) { builder.AddOffset(0, uuidOffset.Value, 0); }
  public static void AddDamage(FlatBufferBuilder builder, int damage) { builder.AddInt(1, damage, 0); }
  public static Offset<HittingInfo> EndHittingInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<HittingInfo>(o);
  }
};


}
