// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Notify_DisappearActor : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Notify_DisappearActor GetRootAsNotify_DisappearActor(ByteBuffer _bb) { return GetRootAsNotify_DisappearActor(_bb, new Notify_DisappearActor()); }
  public static Notify_DisappearActor GetRootAsNotify_DisappearActor(ByteBuffer _bb, Notify_DisappearActor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Notify_DisappearActor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Uuids(int j) { int o = __p.__offset(4); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int UuidsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Notify_DisappearActor> CreateNotify_DisappearActor(FlatBufferBuilder builder,
      VectorOffset uuidsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Notify_DisappearActor.AddUuids(builder, uuidsOffset);
    return Notify_DisappearActor.EndNotify_DisappearActor(builder);
  }

  public static void StartNotify_DisappearActor(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUuids(FlatBufferBuilder builder, VectorOffset uuidsOffset) { builder.AddOffset(0, uuidsOffset.Value, 0); }
  public static VectorOffset CreateUuidsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartUuidsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Notify_DisappearActor> EndNotify_DisappearActor(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Notify_DisappearActor>(o);
  }
};


}
