// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Notify_AppearActor : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Notify_AppearActor GetRootAsNotify_AppearActor(ByteBuffer _bb) { return GetRootAsNotify_AppearActor(_bb, new Notify_AppearActor()); }
  public static Notify_AppearActor GetRootAsNotify_AppearActor(ByteBuffer _bb, Notify_AppearActor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Notify_AppearActor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public RemotePC? RemotePc(int j) { int o = __p.__offset(4); return o != 0 ? (RemotePC?)(new RemotePC()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RemotePcLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Monster? Monster(int j) { int o = __p.__offset(6); return o != 0 ? (Monster?)(new Monster()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MonsterLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Notify_AppearActor> CreateNotify_AppearActor(FlatBufferBuilder builder,
      VectorOffset remote_pcOffset = default(VectorOffset),
      VectorOffset monsterOffset = default(VectorOffset)) {
    builder.StartObject(2);
    Notify_AppearActor.AddMonster(builder, monsterOffset);
    Notify_AppearActor.AddRemotePc(builder, remote_pcOffset);
    return Notify_AppearActor.EndNotify_AppearActor(builder);
  }

  public static void StartNotify_AppearActor(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddRemotePc(FlatBufferBuilder builder, VectorOffset remotePcOffset) { builder.AddOffset(0, remotePcOffset.Value, 0); }
  public static VectorOffset CreateRemotePcVector(FlatBufferBuilder builder, Offset<RemotePC>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartRemotePcVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMonster(FlatBufferBuilder builder, VectorOffset monsterOffset) { builder.AddOffset(1, monsterOffset.Value, 0); }
  public static VectorOffset CreateMonsterVector(FlatBufferBuilder builder, Offset<Monster>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartMonsterVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Notify_AppearActor> EndNotify_AppearActor(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Notify_AppearActor>(o);
  }
};


}
