// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Notify_WorldLogicError : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Notify_WorldLogicError GetRootAsNotify_WorldLogicError(ByteBuffer _bb) { return GetRootAsNotify_WorldLogicError(_bb, new Notify_WorldLogicError()); }
  public static Notify_WorldLogicError GetRootAsNotify_WorldLogicError(ByteBuffer _bb, Notify_WorldLogicError obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Notify_WorldLogicError __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<Notify_WorldLogicError> CreateNotify_WorldLogicError(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    Notify_WorldLogicError.AddErrorCode(builder, error_code);
    return Notify_WorldLogicError.EndNotify_WorldLogicError(builder);
  }

  public static void StartNotify_WorldLogicError(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<Notify_WorldLogicError> EndNotify_WorldLogicError(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Notify_WorldLogicError>(o);
  }
};


}
