// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Notify_Move : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Notify_Move GetRootAsNotify_Move(ByteBuffer _bb) { return GetRootAsNotify_Move(_bb, new Notify_Move()); }
  public static Notify_Move GetRootAsNotify_Move(ByteBuffer _bb, Notify_Move obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Notify_Move __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUuidBytes() { return __p.__vector_as_arraysegment(4); }
  public MoveInfo? Move { get { int o = __p.__offset(6); return o != 0 ? (MoveInfo?)(new MoveInfo()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartNotify_Move(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddUuid(FlatBufferBuilder builder, StringOffset uuidOffset) { builder.AddOffset(0, uuidOffset.Value, 0); }
  public static void AddMove(FlatBufferBuilder builder, Offset<MoveInfo> moveOffset) { builder.AddStruct(1, moveOffset.Value, 0); }
  public static Offset<Notify_Move> EndNotify_Move(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Notify_Move>(o);
  }
};


}
