// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Notify_EnterZone : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Notify_EnterZone GetRootAsNotify_EnterZone(ByteBuffer _bb) { return GetRootAsNotify_EnterZone(_bb, new Notify_EnterZone()); }
  public static Notify_EnterZone GetRootAsNotify_EnterZone(ByteBuffer _bb, Notify_EnterZone obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Notify_EnterZone __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int MapId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public MoveInfo? Move { get { int o = __p.__offset(6); return o != 0 ? (MoveInfo?)(new MoveInfo()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartNotify_EnterZone(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddMapId(FlatBufferBuilder builder, int mapId) { builder.AddInt(0, mapId, 0); }
  public static void AddMove(FlatBufferBuilder builder, Offset<MoveInfo> moveOffset) { builder.AddStruct(1, moveOffset.Value, 0); }
  public static Offset<Notify_EnterZone> EndNotify_EnterZone(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Notify_EnterZone>(o);
  }
};


}
