// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Notify_Attack : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Notify_Attack GetRootAsNotify_Attack(ByteBuffer _bb) { return GetRootAsNotify_Attack(_bb, new Notify_Attack()); }
  public static Notify_Attack GetRootAsNotify_Attack(ByteBuffer _bb, Notify_Attack obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Notify_Attack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUuidBytes() { return __p.__vector_as_arraysegment(4); }
  public float Rotation { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Notify_Attack> CreateNotify_Attack(FlatBufferBuilder builder,
      StringOffset uuidOffset = default(StringOffset),
      float rotation = 0.0f) {
    builder.StartObject(2);
    Notify_Attack.AddRotation(builder, rotation);
    Notify_Attack.AddUuid(builder, uuidOffset);
    return Notify_Attack.EndNotify_Attack(builder);
  }

  public static void StartNotify_Attack(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddUuid(FlatBufferBuilder builder, StringOffset uuidOffset) { builder.AddOffset(0, uuidOffset.Value, 0); }
  public static void AddRotation(FlatBufferBuilder builder, float rotation) { builder.AddFloat(1, rotation, 0.0f); }
  public static Offset<Notify_Attack> EndNotify_Attack(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Notify_Attack>(o);
  }
};


}
