// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.world
{

using System;
using FlatBuffers;

public struct RemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoteCharacter GetRootAsRemoteCharacter(ByteBuffer _bb) { return GetRootAsRemoteCharacter(_bb, new RemoteCharacter()); }
  public static RemoteCharacter GetRootAsRemoteCharacter(ByteBuffer _bb, RemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetUuidBytes() { return __p.__vector_as_arraysegment(4); }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public protocol.ClassType ClassType { get { int o = __p.__offset(8); return o != 0 ? (protocol.ClassType)__p.bb.GetInt(o + __p.bb_pos) : protocol.ClassType.NONE; } }
  public int Level { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxHp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Hp { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxMp { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Mp { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public protocol.Vec3? Pos { get { int o = __p.__offset(20); return o != 0 ? (protocol.Vec3?)(new protocol.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float RotationY { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(10); }
  public static void AddUuid(FlatBufferBuilder builder, StringOffset uuidOffset) { builder.AddOffset(0, uuidOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, protocol.ClassType classType) { builder.AddInt(2, (int)classType, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(3, level, 0); }
  public static void AddMaxHp(FlatBufferBuilder builder, int maxHp) { builder.AddInt(4, maxHp, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(5, hp, 0); }
  public static void AddMaxMp(FlatBufferBuilder builder, int maxMp) { builder.AddInt(6, maxMp, 0); }
  public static void AddMp(FlatBufferBuilder builder, int mp) { builder.AddInt(7, mp, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<protocol.Vec3> posOffset) { builder.AddStruct(8, posOffset.Value, 0); }
  public static void AddRotationY(FlatBufferBuilder builder, float rotationY) { builder.AddFloat(9, rotationY, 0.0f); }
  public static Offset<RemoteCharacter> EndRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoteCharacter>(o);
  }
};


}
