// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Reply_EnterWorldNextFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Reply_EnterWorldNextFailed GetRootAsReply_EnterWorldNextFailed(ByteBuffer _bb) { return GetRootAsReply_EnterWorldNextFailed(_bb, new Reply_EnterWorldNextFailed()); }
  public static Reply_EnterWorldNextFailed GetRootAsReply_EnterWorldNextFailed(ByteBuffer _bb, Reply_EnterWorldNextFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Reply_EnterWorldNextFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<Reply_EnterWorldNextFailed> CreateReply_EnterWorldNextFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    Reply_EnterWorldNextFailed.AddErrorCode(builder, error_code);
    return Reply_EnterWorldNextFailed.EndReply_EnterWorldNextFailed(builder);
  }

  public static void StartReply_EnterWorldNextFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<Reply_EnterWorldNextFailed> EndReply_EnterWorldNextFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Reply_EnterWorldNextFailed>(o);
  }
};


}
