// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.world
{

using System;
using FlatBuffers;

public struct ReplyEnterWorldSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyEnterWorldSuccess GetRootAsReplyEnterWorldSuccess(ByteBuffer _bb) { return GetRootAsReplyEnterWorldSuccess(_bb, new ReplyEnterWorldSuccess()); }
  public static ReplyEnterWorldSuccess GetRootAsReplyEnterWorldSuccess(ByteBuffer _bb, ReplyEnterWorldSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyEnterWorldSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public LocalCharacter? LocalCharacter { get { int o = __p.__offset(4); return o != 0 ? (LocalCharacter?)(new LocalCharacter()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<ReplyEnterWorldSuccess> CreateReplyEnterWorldSuccess(FlatBufferBuilder builder,
      Offset<LocalCharacter> local_characterOffset = default(Offset<LocalCharacter>)) {
    builder.StartObject(1);
    ReplyEnterWorldSuccess.AddLocalCharacter(builder, local_characterOffset);
    return ReplyEnterWorldSuccess.EndReplyEnterWorldSuccess(builder);
  }

  public static void StartReplyEnterWorldSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddLocalCharacter(FlatBufferBuilder builder, Offset<LocalCharacter> localCharacterOffset) { builder.AddOffset(0, localCharacterOffset.Value, 0); }
  public static Offset<ReplyEnterWorldSuccess> EndReplyEnterWorldSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReplyEnterWorldSuccess>(o);
  }
};


}
