// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.world
{

using System;
using FlatBuffers;

public struct ReplyEnterWorldFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyEnterWorldFailed GetRootAsReplyEnterWorldFailed(ByteBuffer _bb) { return GetRootAsReplyEnterWorldFailed(_bb, new ReplyEnterWorldFailed()); }
  public static ReplyEnterWorldFailed GetRootAsReplyEnterWorldFailed(ByteBuffer _bb, ReplyEnterWorldFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyEnterWorldFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<ReplyEnterWorldFailed> CreateReplyEnterWorldFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    ReplyEnterWorldFailed.AddErrorCode(builder, error_code);
    return ReplyEnterWorldFailed.EndReplyEnterWorldFailed(builder);
  }

  public static void StartReplyEnterWorldFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<ReplyEnterWorldFailed> EndReplyEnterWorldFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReplyEnterWorldFailed>(o);
  }
};


}
