// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Request_EnterWorld : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Request_EnterWorld GetRootAsRequest_EnterWorld(ByteBuffer _bb) { return GetRootAsRequest_EnterWorld(_bb, new Request_EnterWorld()); }
  public static Request_EnterWorld GetRootAsRequest_EnterWorld(ByteBuffer _bb, Request_EnterWorld obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Request_EnterWorld __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Request_EnterWorld> CreateRequest_EnterWorld(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    Request_EnterWorld.AddCharacterId(builder, character_id);
    return Request_EnterWorld.EndRequest_EnterWorld(builder);
  }

  public static void StartRequest_EnterWorld(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<Request_EnterWorld> EndRequest_EnterWorld(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Request_EnterWorld>(o);
  }
};


}
