// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.world
{

using global::System;
using global::FlatBuffers;

public struct Request_Attack : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Request_Attack GetRootAsRequest_Attack(ByteBuffer _bb) { return GetRootAsRequest_Attack(_bb, new Request_Attack()); }
  public static Request_Attack GetRootAsRequest_Attack(ByteBuffer _bb, Request_Attack obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Request_Attack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Rotation { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Request_Attack> CreateRequest_Attack(FlatBufferBuilder builder,
      float rotation = 0.0f) {
    builder.StartObject(1);
    Request_Attack.AddRotation(builder, rotation);
    return Request_Attack.EndRequest_Attack(builder);
  }

  public static void StartRequest_Attack(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRotation(FlatBufferBuilder builder, float rotation) { builder.AddFloat(0, rotation, 0.0f); }
  public static Offset<Request_Attack> EndRequest_Attack(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Request_Attack>(o);
  }
};


}
