// automatically generated by the FlatBuffers compiler, do not modify

namespace mmog.protocol
{

using System;
using FlatBuffers;

public enum ErrorCode : int
{
 SUCCESS = 0,
 FATAL_ERROR = 1,
 INVALID_SESSION = 10,
 INVALID_STRING = 20,
 JOIN_ACC_NAME_ALREADY = 100,
 JOIN_CANNOT_ACC_CREATE = 101,
 LOGIN_INCORRECT_ACC_NAME_OR_PASSWORD = 200,
 LOGIN_ALREADY = 201,
 CREATE_CHARACTER_NAME_ALREADY = 301,
 CREATE_CHARACTER_CANNOT_CREATE = 302,
 ENTER_GAME_INVALID_CHARACTER = 401,
 ENTER_GAME_INVALID_STATE = 402,
};

public enum MessageT : byte
{
 NONE = 0,
 RequestLogin = 1,
 LoginFailed = 2,
 LoginSuccess = 3,
 RequestJoin = 4,
 JoinFailed = 5,
 JoinSuccess = 6,
 RequestCharacterList = 7,
 CharacterListFailed = 8,
 CharacterList = 9,
 RequestCreateCharacter = 10,
 CreateCharacterFailed = 11,
 CreateCharacterSuccess = 12,
 RequestDeleteCharacter = 13,
 DeleteCharacterFailed = 14,
 DeleteCharacterSuccess = 15,
 RequestEnterGame = 16,
 EnterGameFailed = 17,
 EnterGameSuccess = 18,
 SpawnRemoteCharacter = 19,
 MoveCharacter = 20,
};

public struct Vec2 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Vec2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }

  public static Offset<Vec2> CreateVec2(FlatBufferBuilder builder, float X, float Y) {
    builder.Prep(4, 8);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<Vec2>(builder.Offset);
  }
};

public struct Vec3 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Vec3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<Vec3> CreateVec3(FlatBufferBuilder builder, float X, float Y, float Z) {
    builder.Prep(4, 12);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<Vec3>(builder.Offset);
  }
};

public struct CharacterSimple : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CharacterSimple GetRootAsCharacterSimple(ByteBuffer _bb) { return GetRootAsCharacterSimple(_bb, new CharacterSimple()); }
  public static CharacterSimple GetRootAsCharacterSimple(ByteBuffer _bb, CharacterSimple obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CharacterSimple __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public int ClassType { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Level { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<CharacterSimple> CreateCharacterSimple(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset),
      int class_type = 0,
      int level = 0) {
    builder.StartObject(4);
    CharacterSimple.AddLevel(builder, level);
    CharacterSimple.AddClassType(builder, class_type);
    CharacterSimple.AddName(builder, nameOffset);
    CharacterSimple.AddId(builder, id);
    return CharacterSimple.EndCharacterSimple(builder);
  }

  public static void StartCharacterSimple(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, int classType) { builder.AddInt(2, classType, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(3, level, 0); }
  public static Offset<CharacterSimple> EndCharacterSimple(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CharacterSimple>(o);
  }
};

public struct PlayerCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PlayerCharacter GetRootAsPlayerCharacter(ByteBuffer _bb) { return GetRootAsPlayerCharacter(_bb, new PlayerCharacter()); }
  public static PlayerCharacter GetRootAsPlayerCharacter(ByteBuffer _bb, PlayerCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PlayerCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public int ClassType { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Exp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Level { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Hp { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Mp { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Att { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Def { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ZoneId { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Vec3? Pos { get { int o = __p.__offset(24); return o != 0 ? (Vec3?)(new Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float RotationY { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public Vec3? Direction { get { int o = __p.__offset(28); return o != 0 ? (Vec3?)(new Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Speed { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartPlayerCharacter(FlatBufferBuilder builder) { builder.StartObject(14); }
  public static void AddUid(FlatBufferBuilder builder, int uid) { builder.AddInt(0, uid, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, int classType) { builder.AddInt(2, classType, 0); }
  public static void AddExp(FlatBufferBuilder builder, int exp) { builder.AddInt(3, exp, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(4, level, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(5, hp, 0); }
  public static void AddMp(FlatBufferBuilder builder, int mp) { builder.AddInt(6, mp, 0); }
  public static void AddAtt(FlatBufferBuilder builder, int att) { builder.AddInt(7, att, 0); }
  public static void AddDef(FlatBufferBuilder builder, int def) { builder.AddInt(8, def, 0); }
  public static void AddZoneId(FlatBufferBuilder builder, int zoneId) { builder.AddInt(9, zoneId, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<Vec3> posOffset) { builder.AddStruct(10, posOffset.Value, 0); }
  public static void AddRotationY(FlatBufferBuilder builder, float rotationY) { builder.AddFloat(11, rotationY, 0.0f); }
  public static void AddDirection(FlatBufferBuilder builder, Offset<Vec3> directionOffset) { builder.AddStruct(12, directionOffset.Value, 0); }
  public static void AddSpeed(FlatBufferBuilder builder, float speed) { builder.AddFloat(13, speed, 0.0f); }
  public static Offset<PlayerCharacter> EndPlayerCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PlayerCharacter>(o);
  }
};

public struct RemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoteCharacter GetRootAsRemoteCharacter(ByteBuffer _bb) { return GetRootAsRemoteCharacter(_bb, new RemoteCharacter()); }
  public static RemoteCharacter GetRootAsRemoteCharacter(ByteBuffer _bb, RemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public int ClassType { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Level { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Hp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Mp { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Vec3? Pos { get { int o = __p.__offset(16); return o != 0 ? (Vec3?)(new Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float RotationY { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public Vec3? Direction { get { int o = __p.__offset(20); return o != 0 ? (Vec3?)(new Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Speed { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(10); }
  public static void AddUid(FlatBufferBuilder builder, int uid) { builder.AddInt(0, uid, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, int classType) { builder.AddInt(2, classType, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(3, level, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(4, hp, 0); }
  public static void AddMp(FlatBufferBuilder builder, int mp) { builder.AddInt(5, mp, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<Vec3> posOffset) { builder.AddStruct(6, posOffset.Value, 0); }
  public static void AddRotationY(FlatBufferBuilder builder, float rotationY) { builder.AddFloat(7, rotationY, 0.0f); }
  public static void AddDirection(FlatBufferBuilder builder, Offset<Vec3> directionOffset) { builder.AddStruct(8, directionOffset.Value, 0); }
  public static void AddSpeed(FlatBufferBuilder builder, float speed) { builder.AddFloat(9, speed, 0.0f); }
  public static Offset<RemoteCharacter> EndRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoteCharacter>(o);
  }
};

public struct RequestLogin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestLogin GetRootAsRequestLogin(ByteBuffer _bb) { return GetRootAsRequestLogin(_bb, new RequestLogin()); }
  public static RequestLogin GetRootAsRequestLogin(ByteBuffer _bb, RequestLogin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestLogin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string AccName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetAccNameBytes() { return __p.__vector_as_arraysegment(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<RequestLogin> CreateRequestLogin(FlatBufferBuilder builder,
      StringOffset acc_nameOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartObject(2);
    RequestLogin.AddPassword(builder, passwordOffset);
    RequestLogin.AddAccName(builder, acc_nameOffset);
    return RequestLogin.EndRequestLogin(builder);
  }

  public static void StartRequestLogin(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAccName(FlatBufferBuilder builder, StringOffset accNameOffset) { builder.AddOffset(0, accNameOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static Offset<RequestLogin> EndRequestLogin(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestLogin>(o);
  }
};

public struct LoginFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginFailed GetRootAsLoginFailed(ByteBuffer _bb) { return GetRootAsLoginFailed(_bb, new LoginFailed()); }
  public static LoginFailed GetRootAsLoginFailed(ByteBuffer _bb, LoginFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : ErrorCode.SUCCESS; } }

  public static Offset<LoginFailed> CreateLoginFailed(FlatBufferBuilder builder,
      ErrorCode error_code = ErrorCode.SUCCESS) {
    builder.StartObject(1);
    LoginFailed.AddErrorCode(builder, error_code);
    return LoginFailed.EndLoginFailed(builder);
  }

  public static void StartLoginFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<LoginFailed> EndLoginFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginFailed>(o);
  }
};

public struct LoginSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LoginSuccess GetRootAsLoginSuccess(ByteBuffer _bb) { return GetRootAsLoginSuccess(_bb, new LoginSuccess()); }
  public static LoginSuccess GetRootAsLoginSuccess(ByteBuffer _bb, LoginSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LoginSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string SessionId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetSessionIdBytes() { return __p.__vector_as_arraysegment(4); }

  public static Offset<LoginSuccess> CreateLoginSuccess(FlatBufferBuilder builder,
      StringOffset session_idOffset = default(StringOffset)) {
    builder.StartObject(1);
    LoginSuccess.AddSessionId(builder, session_idOffset);
    return LoginSuccess.EndLoginSuccess(builder);
  }

  public static void StartLoginSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSessionId(FlatBufferBuilder builder, StringOffset sessionIdOffset) { builder.AddOffset(0, sessionIdOffset.Value, 0); }
  public static Offset<LoginSuccess> EndLoginSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LoginSuccess>(o);
  }
};

public struct RequestJoin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestJoin GetRootAsRequestJoin(ByteBuffer _bb) { return GetRootAsRequestJoin(_bb, new RequestJoin()); }
  public static RequestJoin GetRootAsRequestJoin(ByteBuffer _bb, RequestJoin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestJoin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string AccName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetAccNameBytes() { return __p.__vector_as_arraysegment(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<RequestJoin> CreateRequestJoin(FlatBufferBuilder builder,
      StringOffset acc_nameOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartObject(2);
    RequestJoin.AddPassword(builder, passwordOffset);
    RequestJoin.AddAccName(builder, acc_nameOffset);
    return RequestJoin.EndRequestJoin(builder);
  }

  public static void StartRequestJoin(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAccName(FlatBufferBuilder builder, StringOffset accNameOffset) { builder.AddOffset(0, accNameOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static Offset<RequestJoin> EndRequestJoin(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestJoin>(o);
  }
};

public struct JoinFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static JoinFailed GetRootAsJoinFailed(ByteBuffer _bb) { return GetRootAsJoinFailed(_bb, new JoinFailed()); }
  public static JoinFailed GetRootAsJoinFailed(ByteBuffer _bb, JoinFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public JoinFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : ErrorCode.SUCCESS; } }

  public static Offset<JoinFailed> CreateJoinFailed(FlatBufferBuilder builder,
      ErrorCode error_code = ErrorCode.SUCCESS) {
    builder.StartObject(1);
    JoinFailed.AddErrorCode(builder, error_code);
    return JoinFailed.EndJoinFailed(builder);
  }

  public static void StartJoinFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<JoinFailed> EndJoinFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<JoinFailed>(o);
  }
};

public struct JoinSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static JoinSuccess GetRootAsJoinSuccess(ByteBuffer _bb) { return GetRootAsJoinSuccess(_bb, new JoinSuccess()); }
  public static JoinSuccess GetRootAsJoinSuccess(ByteBuffer _bb, JoinSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public JoinSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartJoinSuccess(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<JoinSuccess> EndJoinSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<JoinSuccess>(o);
  }
};

public struct RequestCharacterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestCharacterList GetRootAsRequestCharacterList(ByteBuffer _bb) { return GetRootAsRequestCharacterList(_bb, new RequestCharacterList()); }
  public static RequestCharacterList GetRootAsRequestCharacterList(ByteBuffer _bb, RequestCharacterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestCharacterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRequestCharacterList(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<RequestCharacterList> EndRequestCharacterList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestCharacterList>(o);
  }
};

public struct CharacterListFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CharacterListFailed GetRootAsCharacterListFailed(ByteBuffer _bb) { return GetRootAsCharacterListFailed(_bb, new CharacterListFailed()); }
  public static CharacterListFailed GetRootAsCharacterListFailed(ByteBuffer _bb, CharacterListFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CharacterListFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : ErrorCode.SUCCESS; } }

  public static Offset<CharacterListFailed> CreateCharacterListFailed(FlatBufferBuilder builder,
      ErrorCode error_code = ErrorCode.SUCCESS) {
    builder.StartObject(1);
    CharacterListFailed.AddErrorCode(builder, error_code);
    return CharacterListFailed.EndCharacterListFailed(builder);
  }

  public static void StartCharacterListFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<CharacterListFailed> EndCharacterListFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CharacterListFailed>(o);
  }
};

public struct CharacterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CharacterList GetRootAsCharacterList(ByteBuffer _bb) { return GetRootAsCharacterList(_bb, new CharacterList()); }
  public static CharacterList GetRootAsCharacterList(ByteBuffer _bb, CharacterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CharacterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CharacterSimple? CharacterList(int j) { int o = __p.__offset(4); return o != 0 ? (CharacterSimple?)(new CharacterSimple()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CharacterListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<CharacterList> CreateCharacterList(FlatBufferBuilder builder,
      VectorOffset character_listOffset = default(VectorOffset)) {
    builder.StartObject(1);
    CharacterList.AddCharacterList(builder, character_listOffset);
    return CharacterList.EndCharacterList(builder);
  }

  public static void StartCharacterList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterList(FlatBufferBuilder builder, VectorOffset characterListOffset) { builder.AddOffset(0, characterListOffset.Value, 0); }
  public static VectorOffset CreateCharacterListVector(FlatBufferBuilder builder, Offset<CharacterSimple>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartCharacterListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<CharacterList> EndCharacterList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CharacterList>(o);
  }
};

public struct RequestCreateCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestCreateCharacter GetRootAsRequestCreateCharacter(ByteBuffer _bb) { return GetRootAsRequestCreateCharacter(_bb, new RequestCreateCharacter()); }
  public static RequestCreateCharacter GetRootAsRequestCreateCharacter(ByteBuffer _bb, RequestCreateCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestCreateCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public int ClassType { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<RequestCreateCharacter> CreateRequestCreateCharacter(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      int class_type = 0) {
    builder.StartObject(2);
    RequestCreateCharacter.AddClassType(builder, class_type);
    RequestCreateCharacter.AddName(builder, nameOffset);
    return RequestCreateCharacter.EndRequestCreateCharacter(builder);
  }

  public static void StartRequestCreateCharacter(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, int classType) { builder.AddInt(1, classType, 0); }
  public static Offset<RequestCreateCharacter> EndRequestCreateCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestCreateCharacter>(o);
  }
};

public struct CreateCharacterFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CreateCharacterFailed GetRootAsCreateCharacterFailed(ByteBuffer _bb) { return GetRootAsCreateCharacterFailed(_bb, new CreateCharacterFailed()); }
  public static CreateCharacterFailed GetRootAsCreateCharacterFailed(ByteBuffer _bb, CreateCharacterFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CreateCharacterFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : ErrorCode.SUCCESS; } }

  public static Offset<CreateCharacterFailed> CreateCreateCharacterFailed(FlatBufferBuilder builder,
      ErrorCode error_code = ErrorCode.SUCCESS) {
    builder.StartObject(1);
    CreateCharacterFailed.AddErrorCode(builder, error_code);
    return CreateCharacterFailed.EndCreateCharacterFailed(builder);
  }

  public static void StartCreateCharacterFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<CreateCharacterFailed> EndCreateCharacterFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CreateCharacterFailed>(o);
  }
};

public struct CreateCharacterSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CreateCharacterSuccess GetRootAsCreateCharacterSuccess(ByteBuffer _bb) { return GetRootAsCreateCharacterSuccess(_bb, new CreateCharacterSuccess()); }
  public static CreateCharacterSuccess GetRootAsCreateCharacterSuccess(ByteBuffer _bb, CreateCharacterSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CreateCharacterSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CharacterSimple? Character { get { int o = __p.__offset(4); return o != 0 ? (CharacterSimple?)(new CharacterSimple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<CreateCharacterSuccess> CreateCreateCharacterSuccess(FlatBufferBuilder builder,
      Offset<CharacterSimple> characterOffset = default(Offset<CharacterSimple>)) {
    builder.StartObject(1);
    CreateCharacterSuccess.AddCharacter(builder, characterOffset);
    return CreateCharacterSuccess.EndCreateCharacterSuccess(builder);
  }

  public static void StartCreateCharacterSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacter(FlatBufferBuilder builder, Offset<CharacterSimple> characterOffset) { builder.AddOffset(0, characterOffset.Value, 0); }
  public static Offset<CreateCharacterSuccess> EndCreateCharacterSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CreateCharacterSuccess>(o);
  }
};

public struct RequestDeleteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestDeleteCharacter GetRootAsRequestDeleteCharacter(ByteBuffer _bb) { return GetRootAsRequestDeleteCharacter(_bb, new RequestDeleteCharacter()); }
  public static RequestDeleteCharacter GetRootAsRequestDeleteCharacter(ByteBuffer _bb, RequestDeleteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestDeleteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<RequestDeleteCharacter> CreateRequestDeleteCharacter(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    RequestDeleteCharacter.AddCharacterId(builder, character_id);
    return RequestDeleteCharacter.EndRequestDeleteCharacter(builder);
  }

  public static void StartRequestDeleteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<RequestDeleteCharacter> EndRequestDeleteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestDeleteCharacter>(o);
  }
};

public struct DeleteCharacterFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DeleteCharacterFailed GetRootAsDeleteCharacterFailed(ByteBuffer _bb) { return GetRootAsDeleteCharacterFailed(_bb, new DeleteCharacterFailed()); }
  public static DeleteCharacterFailed GetRootAsDeleteCharacterFailed(ByteBuffer _bb, DeleteCharacterFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DeleteCharacterFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : ErrorCode.SUCCESS; } }

  public static Offset<DeleteCharacterFailed> CreateDeleteCharacterFailed(FlatBufferBuilder builder,
      ErrorCode error_code = ErrorCode.SUCCESS) {
    builder.StartObject(1);
    DeleteCharacterFailed.AddErrorCode(builder, error_code);
    return DeleteCharacterFailed.EndDeleteCharacterFailed(builder);
  }

  public static void StartDeleteCharacterFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<DeleteCharacterFailed> EndDeleteCharacterFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DeleteCharacterFailed>(o);
  }
};

public struct DeleteCharacterSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DeleteCharacterSuccess GetRootAsDeleteCharacterSuccess(ByteBuffer _bb) { return GetRootAsDeleteCharacterSuccess(_bb, new DeleteCharacterSuccess()); }
  public static DeleteCharacterSuccess GetRootAsDeleteCharacterSuccess(ByteBuffer _bb, DeleteCharacterSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DeleteCharacterSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<DeleteCharacterSuccess> CreateDeleteCharacterSuccess(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    DeleteCharacterSuccess.AddCharacterId(builder, character_id);
    return DeleteCharacterSuccess.EndDeleteCharacterSuccess(builder);
  }

  public static void StartDeleteCharacterSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<DeleteCharacterSuccess> EndDeleteCharacterSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DeleteCharacterSuccess>(o);
  }
};

public struct RequestEnterGame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestEnterGame GetRootAsRequestEnterGame(ByteBuffer _bb) { return GetRootAsRequestEnterGame(_bb, new RequestEnterGame()); }
  public static RequestEnterGame GetRootAsRequestEnterGame(ByteBuffer _bb, RequestEnterGame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestEnterGame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<RequestEnterGame> CreateRequestEnterGame(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    RequestEnterGame.AddCharacterId(builder, character_id);
    return RequestEnterGame.EndRequestEnterGame(builder);
  }

  public static void StartRequestEnterGame(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<RequestEnterGame> EndRequestEnterGame(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestEnterGame>(o);
  }
};

public struct EnterGameFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static EnterGameFailed GetRootAsEnterGameFailed(ByteBuffer _bb) { return GetRootAsEnterGameFailed(_bb, new EnterGameFailed()); }
  public static EnterGameFailed GetRootAsEnterGameFailed(ByteBuffer _bb, EnterGameFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EnterGameFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : ErrorCode.SUCCESS; } }

  public static Offset<EnterGameFailed> CreateEnterGameFailed(FlatBufferBuilder builder,
      ErrorCode error_code = ErrorCode.SUCCESS) {
    builder.StartObject(1);
    EnterGameFailed.AddErrorCode(builder, error_code);
    return EnterGameFailed.EndEnterGameFailed(builder);
  }

  public static void StartEnterGameFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<EnterGameFailed> EndEnterGameFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EnterGameFailed>(o);
  }
};

public struct EnterGameSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static EnterGameSuccess GetRootAsEnterGameSuccess(ByteBuffer _bb) { return GetRootAsEnterGameSuccess(_bb, new EnterGameSuccess()); }
  public static EnterGameSuccess GetRootAsEnterGameSuccess(ByteBuffer _bb, EnterGameSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EnterGameSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PlayerCharacter? Character { get { int o = __p.__offset(4); return o != 0 ? (PlayerCharacter?)(new PlayerCharacter()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<EnterGameSuccess> CreateEnterGameSuccess(FlatBufferBuilder builder,
      Offset<PlayerCharacter> characterOffset = default(Offset<PlayerCharacter>)) {
    builder.StartObject(1);
    EnterGameSuccess.AddCharacter(builder, characterOffset);
    return EnterGameSuccess.EndEnterGameSuccess(builder);
  }

  public static void StartEnterGameSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacter(FlatBufferBuilder builder, Offset<PlayerCharacter> characterOffset) { builder.AddOffset(0, characterOffset.Value, 0); }
  public static Offset<EnterGameSuccess> EndEnterGameSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EnterGameSuccess>(o);
  }
};

public struct SpawnRemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SpawnRemoteCharacter GetRootAsSpawnRemoteCharacter(ByteBuffer _bb) { return GetRootAsSpawnRemoteCharacter(_bb, new SpawnRemoteCharacter()); }
  public static SpawnRemoteCharacter GetRootAsSpawnRemoteCharacter(ByteBuffer _bb, SpawnRemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SpawnRemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public RemoteCharacter? Character { get { int o = __p.__offset(4); return o != 0 ? (RemoteCharacter?)(new RemoteCharacter()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<SpawnRemoteCharacter> CreateSpawnRemoteCharacter(FlatBufferBuilder builder,
      Offset<RemoteCharacter> characterOffset = default(Offset<RemoteCharacter>)) {
    builder.StartObject(1);
    SpawnRemoteCharacter.AddCharacter(builder, characterOffset);
    return SpawnRemoteCharacter.EndSpawnRemoteCharacter(builder);
  }

  public static void StartSpawnRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacter(FlatBufferBuilder builder, Offset<RemoteCharacter> characterOffset) { builder.AddOffset(0, characterOffset.Value, 0); }
  public static Offset<SpawnRemoteCharacter> EndSpawnRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SpawnRemoteCharacter>(o);
  }
};

public struct MoveCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MoveCharacter GetRootAsMoveCharacter(ByteBuffer _bb) { return GetRootAsMoveCharacter(_bb, new MoveCharacter()); }
  public static MoveCharacter GetRootAsMoveCharacter(ByteBuffer _bb, MoveCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MoveCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Vec3? Pos { get { int o = __p.__offset(6); return o != 0 ? (Vec3?)(new Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float RotationY { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public Vec3? Velocity { get { int o = __p.__offset(10); return o != 0 ? (Vec3?)(new Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartMoveCharacter(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddUid(FlatBufferBuilder builder, int uid) { builder.AddInt(0, uid, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<Vec3> posOffset) { builder.AddStruct(1, posOffset.Value, 0); }
  public static void AddRotationY(FlatBufferBuilder builder, float rotationY) { builder.AddFloat(2, rotationY, 0.0f); }
  public static void AddVelocity(FlatBufferBuilder builder, Offset<Vec3> velocityOffset) { builder.AddStruct(3, velocityOffset.Value, 0); }
  public static Offset<MoveCharacter> EndMoveCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MoveCharacter>(o);
  }
};

public struct NetMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static NetMessage GetRootAsNetMessage(ByteBuffer _bb) { return GetRootAsNetMessage(_bb, new NetMessage()); }
  public static NetMessage GetRootAsNetMessage(ByteBuffer _bb, NetMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public NetMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MessageT MessageType { get { int o = __p.__offset(4); return o != 0 ? (MessageT)__p.bb.Get(o + __p.bb_pos) : MessageT.NONE; } }
  public TTable? Message<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o) : null; }

  public static Offset<NetMessage> CreateNetMessage(FlatBufferBuilder builder,
      MessageT message_type = MessageT.NONE,
      int messageOffset = 0) {
    builder.StartObject(2);
    NetMessage.AddMessage(builder, messageOffset);
    NetMessage.AddMessageType(builder, message_type);
    return NetMessage.EndNetMessage(builder);
  }

  public static void StartNetMessage(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddMessageType(FlatBufferBuilder builder, MessageT messageType) { builder.AddByte(0, (byte)messageType, 0); }
  public static void AddMessage(FlatBufferBuilder builder, int messageOffset) { builder.AddOffset(1, messageOffset, 0); }
  public static Offset<NetMessage> EndNetMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NetMessage>(o);
  }
  public static void FinishNetMessageBuffer(FlatBufferBuilder builder, Offset<NetMessage> offset) { builder.Finish(offset.Value); }
};


}
