// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum ClassType : int
{
 NONE = 0,
 Knight = 1,
 Archer = 2,
 Mage = 3,
};


}
