// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum MapType : int
{
 NONE = 0,
 FIELD = 1,
 DUNGEON = 2,
};


}
