// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

public enum MessageT : byte
{
 NONE = 0,
 Notify_UnauthedAccess = 1,
 login_Request_Login = 2,
 login_Reply_LoginFailed = 3,
 login_Reply_LoginSuccess = 4,
 login_Request_Join = 5,
 login_Reply_JoinFailed = 6,
 login_Reply_JoinSuccess = 7,
 login_Request_CharacterList = 8,
 login_Reply_CharacterList = 9,
 login_Request_CreateCharacter = 10,
 login_Reply_CreateCharacterFailed = 11,
 login_Reply_CreateCharacterSuccess = 12,
 login_Request_DeleteCharacter = 13,
 login_Reply_DeleteCharacterFailed = 14,
 login_Reply_DeleteCharacterSuccess = 15,
 world_Request_EnterWorld = 16,
 world_Reply_EnterWorldFailed = 17,
 world_Reply_EnterWorldSuccess = 18,
 world_Request_EnterWorldNext = 19,
 world_Reply_EnterWorldNextFailed = 20,
 world_Reply_EnterWorldNextSuccess = 21,
 world_Notify_WorldLogicError = 22,
 world_Notify_EnterZone = 23,
 world_Notify_AppearActor = 24,
 world_Notify_DisappearActor = 25,
 world_Request_Move = 26,
 world_Request_Attack = 27,
 world_Notify_Move = 28,
 world_Notify_Attack = 29,
 world_Notify_Hit = 30,
};


}
