// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol
{

public enum MessageT : byte
{
 NONE = 0,
 NotifyUnauthedAccess = 1,
 login_RequestLogin = 2,
 login_ReplyLoginFailed = 3,
 login_ReplyLoginSuccess = 4,
 login_RequestJoin = 5,
 login_ReplyJoinFailed = 6,
 login_ReplyJoinSuccess = 7,
 login_RequestCharacterList = 8,
 login_ReplyCharacterList = 9,
 login_RequestCreateCharacter = 10,
 login_ReplyCreateCharacterFailed = 11,
 login_ReplyCreateCharacterSuccess = 12,
 login_RequestDeleteCharacter = 13,
 login_ReplyDeleteCharacterFailed = 14,
 login_ReplyDeleteCharacterSuccess = 15,
 world_RequestEnterWorld = 16,
 world_ReplyEnterWorldFailed = 17,
 world_ReplyEnterWorldSuccess = 18,
 world_ActionMove = 19,
 world_ActionAttack = 20,
 world_NotifyMove = 21,
 world_NotifyAttack = 22,
 world_AppearRemoteCharacter = 23,
 world_DisappearRemoteCharacter = 24,
};


}
