// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol
{

using System;
using FlatBuffers;

public struct NotifyUnauthedAccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static NotifyUnauthedAccess GetRootAsNotifyUnauthedAccess(ByteBuffer _bb) { return GetRootAsNotifyUnauthedAccess(_bb, new NotifyUnauthedAccess()); }
  public static NotifyUnauthedAccess GetRootAsNotifyUnauthedAccess(ByteBuffer _bb, NotifyUnauthedAccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public NotifyUnauthedAccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNotifyUnauthedAccess(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<NotifyUnauthedAccess> EndNotifyUnauthedAccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NotifyUnauthedAccess>(o);
  }
};


}
