// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol
{

using System;
using FlatBuffers;

public enum ErrorCode : int
{
 OK = 0,
 UNEXPECTED = 1,
 DATABASE_FAILED = 2,
 INVALID_SESSION = 10,
 INVALID_STRING = 20,
 LOGIN_INCORRECT_ACC_NAME = 100,
 LOGIN_INCORRECT_ACC_PASSWORD = 101,
 LOGIN_ALREADY = 102,
 JOIN_ACC_NAME_ALREADY = 200,
 JOIN_CANNOT_ACC_CREATE = 201,
 CREATE_CHARACTER_NAME_ALREADY = 301,
 CREATE_CHARACTER_CANNOT_CREATE = 302,
 CREATE_CHARACTER_ATTRIBUTE_NOT_EXIST = 303,
 DELETE_CHARACTER_NOT_EXIST = 401,
 DELETE_CHARACTER_CANNOT_DELETE = 402,
 ENTER_WORLD_INVALID_CHARACTER = 501,
 ENTER_WORLD_INVALID_STATE = 502,
};

public enum ClassType : int
{
 NONE = 0,
 Knight = 1,
 Archer = 2,
 Mage = 3,
};

public enum MapType : int
{
 NONE = 0,
 FIELD = 1,
 DUNGEON = 2,
};

public enum MessageT : byte
{
 NONE = 0,
 NotifyUnauthedAccess = 1,
 login_RequestLogin = 2,
 login_ReplyLoginFailed = 3,
 login_ReplyLoginSuccess = 4,
 login_RequestJoin = 5,
 login_ReplyJoinFailed = 6,
 login_ReplyJoinSuccess = 7,
 login_RequestCharacterList = 8,
 login_ReplyCharacterList = 9,
 login_RequestCreateCharacter = 10,
 login_ReplyCreateCharacterFailed = 11,
 login_ReplyCreateCharacterSuccess = 12,
 login_RequestDeleteCharacter = 13,
 login_ReplyDeleteCharacterFailed = 14,
 login_ReplyDeleteCharacterSuccess = 15,
 world_RequestEnterWorld = 16,
 world_ReplyEnterWorldFailed = 17,
 world_ReplyEnterWorldSuccess = 18,
 world_ActionMove = 19,
 world_ActionAttack = 20,
 world_NotifyMove = 21,
 world_NotifyAttack = 22,
 world_AppearRemoteCharacter = 23,
 world_DisappearRemoteCharacter = 24,
};

public struct NotifyUnauthedAccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static NotifyUnauthedAccess GetRootAsNotifyUnauthedAccess(ByteBuffer _bb) { return GetRootAsNotifyUnauthedAccess(_bb, new NotifyUnauthedAccess()); }
  public static NotifyUnauthedAccess GetRootAsNotifyUnauthedAccess(ByteBuffer _bb, NotifyUnauthedAccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public NotifyUnauthedAccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNotifyUnauthedAccess(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<protocol.NotifyUnauthedAccess> EndNotifyUnauthedAccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.NotifyUnauthedAccess>(o);
  }
};

public struct Character : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Character GetRootAsCharacter(ByteBuffer _bb) { return GetRootAsCharacter(_bb, new Character()); }
  public static Character GetRootAsCharacter(ByteBuffer _bb, Character obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Character __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public protocol.ClassType ClassType { get { int o = __p.__offset(8); return o != 0 ? (protocol.ClassType)__p.bb.GetInt(o + __p.bb_pos) : protocol.ClassType.NONE; } }
  public int Level { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<protocol.login.Character> CreateCharacter(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset),
      protocol.ClassType class_type = protocol.ClassType.NONE,
      int level = 0) {
    builder.StartObject(4);
    Character.AddLevel(builder, level);
    Character.AddClassType(builder, class_type);
    Character.AddName(builder, nameOffset);
    Character.AddId(builder, id);
    return Character.EndCharacter(builder);
  }

  public static void StartCharacter(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, protocol.ClassType classType) { builder.AddInt(2, (int)classType, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(3, level, 0); }
  public static Offset<protocol.login.Character> EndCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.Character>(o);
  }
};

public struct RequestLogin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestLogin GetRootAsRequestLogin(ByteBuffer _bb) { return GetRootAsRequestLogin(_bb, new RequestLogin()); }
  public static RequestLogin GetRootAsRequestLogin(ByteBuffer _bb, RequestLogin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestLogin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string AccName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetAccNameBytes() { return __p.__vector_as_arraysegment(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<protocol.login.RequestLogin> CreateRequestLogin(FlatBufferBuilder builder,
      StringOffset acc_nameOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartObject(2);
    RequestLogin.AddPassword(builder, passwordOffset);
    RequestLogin.AddAccName(builder, acc_nameOffset);
    return RequestLogin.EndRequestLogin(builder);
  }

  public static void StartRequestLogin(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAccName(FlatBufferBuilder builder, StringOffset accNameOffset) { builder.AddOffset(0, accNameOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static Offset<protocol.login.RequestLogin> EndRequestLogin(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.RequestLogin>(o);
  }
};

public struct ReplyLoginFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyLoginFailed GetRootAsReplyLoginFailed(ByteBuffer _bb) { return GetRootAsReplyLoginFailed(_bb, new ReplyLoginFailed()); }
  public static ReplyLoginFailed GetRootAsReplyLoginFailed(ByteBuffer _bb, ReplyLoginFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyLoginFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<protocol.login.ReplyLoginFailed> CreateReplyLoginFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    ReplyLoginFailed.AddErrorCode(builder, error_code);
    return ReplyLoginFailed.EndReplyLoginFailed(builder);
  }

  public static void StartReplyLoginFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<protocol.login.ReplyLoginFailed> EndReplyLoginFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyLoginFailed>(o);
  }
};

public struct ReplyLoginSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyLoginSuccess GetRootAsReplyLoginSuccess(ByteBuffer _bb) { return GetRootAsReplyLoginSuccess(_bb, new ReplyLoginSuccess()); }
  public static ReplyLoginSuccess GetRootAsReplyLoginSuccess(ByteBuffer _bb, ReplyLoginSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyLoginSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartReplyLoginSuccess(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<protocol.login.ReplyLoginSuccess> EndReplyLoginSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyLoginSuccess>(o);
  }
};

public struct RequestJoin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestJoin GetRootAsRequestJoin(ByteBuffer _bb) { return GetRootAsRequestJoin(_bb, new RequestJoin()); }
  public static RequestJoin GetRootAsRequestJoin(ByteBuffer _bb, RequestJoin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestJoin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string AccName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetAccNameBytes() { return __p.__vector_as_arraysegment(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<protocol.login.RequestJoin> CreateRequestJoin(FlatBufferBuilder builder,
      StringOffset acc_nameOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartObject(2);
    RequestJoin.AddPassword(builder, passwordOffset);
    RequestJoin.AddAccName(builder, acc_nameOffset);
    return RequestJoin.EndRequestJoin(builder);
  }

  public static void StartRequestJoin(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAccName(FlatBufferBuilder builder, StringOffset accNameOffset) { builder.AddOffset(0, accNameOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static Offset<protocol.login.RequestJoin> EndRequestJoin(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.RequestJoin>(o);
  }
};

public struct ReplyJoinFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyJoinFailed GetRootAsReplyJoinFailed(ByteBuffer _bb) { return GetRootAsReplyJoinFailed(_bb, new ReplyJoinFailed()); }
  public static ReplyJoinFailed GetRootAsReplyJoinFailed(ByteBuffer _bb, ReplyJoinFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyJoinFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<protocol.login.ReplyJoinFailed> CreateReplyJoinFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    ReplyJoinFailed.AddErrorCode(builder, error_code);
    return ReplyJoinFailed.EndReplyJoinFailed(builder);
  }

  public static void StartReplyJoinFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<protocol.login.ReplyJoinFailed> EndReplyJoinFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyJoinFailed>(o);
  }
};

public struct ReplyJoinSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyJoinSuccess GetRootAsReplyJoinSuccess(ByteBuffer _bb) { return GetRootAsReplyJoinSuccess(_bb, new ReplyJoinSuccess()); }
  public static ReplyJoinSuccess GetRootAsReplyJoinSuccess(ByteBuffer _bb, ReplyJoinSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyJoinSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartReplyJoinSuccess(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<protocol.login.ReplyJoinSuccess> EndReplyJoinSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyJoinSuccess>(o);
  }
};

public struct RequestCharacterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestCharacterList GetRootAsRequestCharacterList(ByteBuffer _bb) { return GetRootAsRequestCharacterList(_bb, new RequestCharacterList()); }
  public static RequestCharacterList GetRootAsRequestCharacterList(ByteBuffer _bb, RequestCharacterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestCharacterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRequestCharacterList(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<protocol.login.RequestCharacterList> EndRequestCharacterList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.RequestCharacterList>(o);
  }
};

public struct ReplyCharacterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyCharacterList GetRootAsReplyCharacterList(ByteBuffer _bb) { return GetRootAsReplyCharacterList(_bb, new ReplyCharacterList()); }
  public static ReplyCharacterList GetRootAsReplyCharacterList(ByteBuffer _bb, ReplyCharacterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyCharacterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.login.Character? List(int j) { int o = __p.__offset(4); return o != 0 ? (protocol.login.Character?)(new protocol.login.Character()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<protocol.login.ReplyCharacterList> CreateReplyCharacterList(FlatBufferBuilder builder,
      VectorOffset listOffset = default(VectorOffset)) {
    builder.StartObject(1);
    ReplyCharacterList.AddList(builder, listOffset);
    return ReplyCharacterList.EndReplyCharacterList(builder);
  }

  public static void StartReplyCharacterList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddList(FlatBufferBuilder builder, VectorOffset listOffset) { builder.AddOffset(0, listOffset.Value, 0); }
  public static VectorOffset CreateListVector(FlatBufferBuilder builder, Offset<protocol.login.Character>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<protocol.login.ReplyCharacterList> EndReplyCharacterList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyCharacterList>(o);
  }
};

public struct RequestCreateCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestCreateCharacter GetRootAsRequestCreateCharacter(ByteBuffer _bb) { return GetRootAsRequestCreateCharacter(_bb, new RequestCreateCharacter()); }
  public static RequestCreateCharacter GetRootAsRequestCreateCharacter(ByteBuffer _bb, RequestCreateCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestCreateCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public protocol.ClassType ClassType { get { int o = __p.__offset(6); return o != 0 ? (protocol.ClassType)__p.bb.GetInt(o + __p.bb_pos) : protocol.ClassType.NONE; } }

  public static Offset<protocol.login.RequestCreateCharacter> CreateRequestCreateCharacter(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      protocol.ClassType class_type = protocol.ClassType.NONE) {
    builder.StartObject(2);
    RequestCreateCharacter.AddClassType(builder, class_type);
    RequestCreateCharacter.AddName(builder, nameOffset);
    return RequestCreateCharacter.EndRequestCreateCharacter(builder);
  }

  public static void StartRequestCreateCharacter(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, protocol.ClassType classType) { builder.AddInt(1, (int)classType, 0); }
  public static Offset<protocol.login.RequestCreateCharacter> EndRequestCreateCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.RequestCreateCharacter>(o);
  }
};

public struct ReplyCreateCharacterFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyCreateCharacterFailed GetRootAsReplyCreateCharacterFailed(ByteBuffer _bb) { return GetRootAsReplyCreateCharacterFailed(_bb, new ReplyCreateCharacterFailed()); }
  public static ReplyCreateCharacterFailed GetRootAsReplyCreateCharacterFailed(ByteBuffer _bb, ReplyCreateCharacterFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyCreateCharacterFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<protocol.login.ReplyCreateCharacterFailed> CreateReplyCreateCharacterFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    ReplyCreateCharacterFailed.AddErrorCode(builder, error_code);
    return ReplyCreateCharacterFailed.EndReplyCreateCharacterFailed(builder);
  }

  public static void StartReplyCreateCharacterFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<protocol.login.ReplyCreateCharacterFailed> EndReplyCreateCharacterFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyCreateCharacterFailed>(o);
  }
};

public struct ReplyCreateCharacterSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyCreateCharacterSuccess GetRootAsReplyCreateCharacterSuccess(ByteBuffer _bb) { return GetRootAsReplyCreateCharacterSuccess(_bb, new ReplyCreateCharacterSuccess()); }
  public static ReplyCreateCharacterSuccess GetRootAsReplyCreateCharacterSuccess(ByteBuffer _bb, ReplyCreateCharacterSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyCreateCharacterSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.login.Character? Character { get { int o = __p.__offset(4); return o != 0 ? (protocol.login.Character?)(new protocol.login.Character()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<protocol.login.ReplyCreateCharacterSuccess> CreateReplyCreateCharacterSuccess(FlatBufferBuilder builder,
      Offset<protocol.login.Character> characterOffset = default(Offset<protocol.login.Character>)) {
    builder.StartObject(1);
    ReplyCreateCharacterSuccess.AddCharacter(builder, characterOffset);
    return ReplyCreateCharacterSuccess.EndReplyCreateCharacterSuccess(builder);
  }

  public static void StartReplyCreateCharacterSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacter(FlatBufferBuilder builder, Offset<protocol.login.Character> characterOffset) { builder.AddOffset(0, characterOffset.Value, 0); }
  public static Offset<protocol.login.ReplyCreateCharacterSuccess> EndReplyCreateCharacterSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyCreateCharacterSuccess>(o);
  }
};

public struct RequestDeleteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestDeleteCharacter GetRootAsRequestDeleteCharacter(ByteBuffer _bb) { return GetRootAsRequestDeleteCharacter(_bb, new RequestDeleteCharacter()); }
  public static RequestDeleteCharacter GetRootAsRequestDeleteCharacter(ByteBuffer _bb, RequestDeleteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestDeleteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<protocol.login.RequestDeleteCharacter> CreateRequestDeleteCharacter(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    RequestDeleteCharacter.AddCharacterId(builder, character_id);
    return RequestDeleteCharacter.EndRequestDeleteCharacter(builder);
  }

  public static void StartRequestDeleteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<protocol.login.RequestDeleteCharacter> EndRequestDeleteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.RequestDeleteCharacter>(o);
  }
};

public struct ReplyDeleteCharacterFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyDeleteCharacterFailed GetRootAsReplyDeleteCharacterFailed(ByteBuffer _bb) { return GetRootAsReplyDeleteCharacterFailed(_bb, new ReplyDeleteCharacterFailed()); }
  public static ReplyDeleteCharacterFailed GetRootAsReplyDeleteCharacterFailed(ByteBuffer _bb, ReplyDeleteCharacterFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyDeleteCharacterFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<protocol.login.ReplyDeleteCharacterFailed> CreateReplyDeleteCharacterFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    ReplyDeleteCharacterFailed.AddErrorCode(builder, error_code);
    return ReplyDeleteCharacterFailed.EndReplyDeleteCharacterFailed(builder);
  }

  public static void StartReplyDeleteCharacterFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<protocol.login.ReplyDeleteCharacterFailed> EndReplyDeleteCharacterFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyDeleteCharacterFailed>(o);
  }
};

public struct ReplyDeleteCharacterSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyDeleteCharacterSuccess GetRootAsReplyDeleteCharacterSuccess(ByteBuffer _bb) { return GetRootAsReplyDeleteCharacterSuccess(_bb, new ReplyDeleteCharacterSuccess()); }
  public static ReplyDeleteCharacterSuccess GetRootAsReplyDeleteCharacterSuccess(ByteBuffer _bb, ReplyDeleteCharacterSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyDeleteCharacterSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<protocol.login.ReplyDeleteCharacterSuccess> CreateReplyDeleteCharacterSuccess(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    ReplyDeleteCharacterSuccess.AddCharacterId(builder, character_id);
    return ReplyDeleteCharacterSuccess.EndReplyDeleteCharacterSuccess(builder);
  }

  public static void StartReplyDeleteCharacterSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<protocol.login.ReplyDeleteCharacterSuccess> EndReplyDeleteCharacterSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.login.ReplyDeleteCharacterSuccess>(o);
  }
};

public struct Vec2 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Vec2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }

  public static Offset<protocol.world.Vec2> CreateVec2(FlatBufferBuilder builder, float X, float Y) {
    builder.Prep(4, 8);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<protocol.world.Vec2>(builder.Offset);
  }
};

public struct Vec3 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Vec3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<protocol.world.Vec3> CreateVec3(FlatBufferBuilder builder, float X, float Y, float Z) {
    builder.Prep(4, 12);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<protocol.world.Vec3>(builder.Offset);
  }
};

public struct LocalCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LocalCharacter GetRootAsLocalCharacter(ByteBuffer _bb) { return GetRootAsLocalCharacter(_bb, new LocalCharacter()); }
  public static LocalCharacter GetRootAsLocalCharacter(ByteBuffer _bb, LocalCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LocalCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public protocol.ClassType ClassType { get { int o = __p.__offset(8); return o != 0 ? (protocol.ClassType)__p.bb.GetInt(o + __p.bb_pos) : protocol.ClassType.NONE; } }
  public int Exp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Level { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxHp { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Hp { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxMp { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Mp { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Att { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Def { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MapId { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public protocol.world.Vec3? Pos { get { int o = __p.__offset(28); return o != 0 ? (protocol.world.Vec3?)(new protocol.world.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float RotationY { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Speed { get { int o = __p.__offset(32); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartLocalCharacter(FlatBufferBuilder builder) { builder.StartObject(15); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(0, uuid, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, protocol.ClassType classType) { builder.AddInt(2, (int)classType, 0); }
  public static void AddExp(FlatBufferBuilder builder, int exp) { builder.AddInt(3, exp, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(4, level, 0); }
  public static void AddMaxHp(FlatBufferBuilder builder, int maxHp) { builder.AddInt(5, maxHp, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(6, hp, 0); }
  public static void AddMaxMp(FlatBufferBuilder builder, int maxMp) { builder.AddInt(7, maxMp, 0); }
  public static void AddMp(FlatBufferBuilder builder, int mp) { builder.AddInt(8, mp, 0); }
  public static void AddAtt(FlatBufferBuilder builder, int att) { builder.AddInt(9, att, 0); }
  public static void AddDef(FlatBufferBuilder builder, int def) { builder.AddInt(10, def, 0); }
  public static void AddMapId(FlatBufferBuilder builder, int mapId) { builder.AddInt(11, mapId, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<protocol.world.Vec3> posOffset) { builder.AddStruct(12, posOffset.Value, 0); }
  public static void AddRotationY(FlatBufferBuilder builder, float rotationY) { builder.AddFloat(13, rotationY, 0.0f); }
  public static void AddSpeed(FlatBufferBuilder builder, float speed) { builder.AddFloat(14, speed, 0.0f); }
  public static Offset<protocol.world.LocalCharacter> EndLocalCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.LocalCharacter>(o);
  }
};

public struct RemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoteCharacter GetRootAsRemoteCharacter(ByteBuffer _bb) { return GetRootAsRemoteCharacter(_bb, new RemoteCharacter()); }
  public static RemoteCharacter GetRootAsRemoteCharacter(ByteBuffer _bb, RemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
  public protocol.ClassType ClassType { get { int o = __p.__offset(8); return o != 0 ? (protocol.ClassType)__p.bb.GetInt(o + __p.bb_pos) : protocol.ClassType.NONE; } }
  public int Level { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxHp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Hp { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxMp { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Mp { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public protocol.world.Vec3? Pos { get { int o = __p.__offset(20); return o != 0 ? (protocol.world.Vec3?)(new protocol.world.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float RotationY { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(10); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(0, uuid, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, protocol.ClassType classType) { builder.AddInt(2, (int)classType, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(3, level, 0); }
  public static void AddMaxHp(FlatBufferBuilder builder, int maxHp) { builder.AddInt(4, maxHp, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(5, hp, 0); }
  public static void AddMaxMp(FlatBufferBuilder builder, int maxMp) { builder.AddInt(6, maxMp, 0); }
  public static void AddMp(FlatBufferBuilder builder, int mp) { builder.AddInt(7, mp, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<protocol.world.Vec3> posOffset) { builder.AddStruct(8, posOffset.Value, 0); }
  public static void AddRotationY(FlatBufferBuilder builder, float rotationY) { builder.AddFloat(9, rotationY, 0.0f); }
  public static Offset<protocol.world.RemoteCharacter> EndRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.RemoteCharacter>(o);
  }
};

public struct RequestEnterWorld : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestEnterWorld GetRootAsRequestEnterWorld(ByteBuffer _bb) { return GetRootAsRequestEnterWorld(_bb, new RequestEnterWorld()); }
  public static RequestEnterWorld GetRootAsRequestEnterWorld(ByteBuffer _bb, RequestEnterWorld obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestEnterWorld __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<protocol.world.RequestEnterWorld> CreateRequestEnterWorld(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    RequestEnterWorld.AddCharacterId(builder, character_id);
    return RequestEnterWorld.EndRequestEnterWorld(builder);
  }

  public static void StartRequestEnterWorld(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<protocol.world.RequestEnterWorld> EndRequestEnterWorld(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.RequestEnterWorld>(o);
  }
};

public struct ReplyEnterWorldFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyEnterWorldFailed GetRootAsReplyEnterWorldFailed(ByteBuffer _bb) { return GetRootAsReplyEnterWorldFailed(_bb, new ReplyEnterWorldFailed()); }
  public static ReplyEnterWorldFailed GetRootAsReplyEnterWorldFailed(ByteBuffer _bb, ReplyEnterWorldFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyEnterWorldFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<protocol.world.ReplyEnterWorldFailed> CreateReplyEnterWorldFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    ReplyEnterWorldFailed.AddErrorCode(builder, error_code);
    return ReplyEnterWorldFailed.EndReplyEnterWorldFailed(builder);
  }

  public static void StartReplyEnterWorldFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<protocol.world.ReplyEnterWorldFailed> EndReplyEnterWorldFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.ReplyEnterWorldFailed>(o);
  }
};

public struct ReplyEnterWorldSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyEnterWorldSuccess GetRootAsReplyEnterWorldSuccess(ByteBuffer _bb) { return GetRootAsReplyEnterWorldSuccess(_bb, new ReplyEnterWorldSuccess()); }
  public static ReplyEnterWorldSuccess GetRootAsReplyEnterWorldSuccess(ByteBuffer _bb, ReplyEnterWorldSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyEnterWorldSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.world.LocalCharacter? LocalCharacter { get { int o = __p.__offset(4); return o != 0 ? (protocol.world.LocalCharacter?)(new protocol.world.LocalCharacter()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<protocol.world.ReplyEnterWorldSuccess> CreateReplyEnterWorldSuccess(FlatBufferBuilder builder,
      Offset<protocol.world.LocalCharacter> local_characterOffset = default(Offset<protocol.world.LocalCharacter>)) {
    builder.StartObject(1);
    ReplyEnterWorldSuccess.AddLocalCharacter(builder, local_characterOffset);
    return ReplyEnterWorldSuccess.EndReplyEnterWorldSuccess(builder);
  }

  public static void StartReplyEnterWorldSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddLocalCharacter(FlatBufferBuilder builder, Offset<protocol.world.LocalCharacter> localCharacterOffset) { builder.AddOffset(0, localCharacterOffset.Value, 0); }
  public static Offset<protocol.world.ReplyEnterWorldSuccess> EndReplyEnterWorldSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.ReplyEnterWorldSuccess>(o);
  }
};

public struct ActionMove : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ActionMove GetRootAsActionMove(ByteBuffer _bb) { return GetRootAsActionMove(_bb, new ActionMove()); }
  public static ActionMove GetRootAsActionMove(ByteBuffer _bb, ActionMove obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ActionMove __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Rotation { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public protocol.world.Vec3? Pos { get { int o = __p.__offset(6); return o != 0 ? (protocol.world.Vec3?)(new protocol.world.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public protocol.world.Vec3? Velocity { get { int o = __p.__offset(8); return o != 0 ? (protocol.world.Vec3?)(new protocol.world.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartActionMove(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddRotation(FlatBufferBuilder builder, float rotation) { builder.AddFloat(0, rotation, 0.0f); }
  public static void AddPos(FlatBufferBuilder builder, Offset<protocol.world.Vec3> posOffset) { builder.AddStruct(1, posOffset.Value, 0); }
  public static void AddVelocity(FlatBufferBuilder builder, Offset<protocol.world.Vec3> velocityOffset) { builder.AddStruct(2, velocityOffset.Value, 0); }
  public static Offset<protocol.world.ActionMove> EndActionMove(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.ActionMove>(o);
  }
};

public struct ActionAttack : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ActionAttack GetRootAsActionAttack(ByteBuffer _bb) { return GetRootAsActionAttack(_bb, new ActionAttack()); }
  public static ActionAttack GetRootAsActionAttack(ByteBuffer _bb, ActionAttack obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ActionAttack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Rotation { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<protocol.world.ActionAttack> CreateActionAttack(FlatBufferBuilder builder,
      float rotation = 0.0f) {
    builder.StartObject(1);
    ActionAttack.AddRotation(builder, rotation);
    return ActionAttack.EndActionAttack(builder);
  }

  public static void StartActionAttack(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddRotation(FlatBufferBuilder builder, float rotation) { builder.AddFloat(0, rotation, 0.0f); }
  public static Offset<protocol.world.ActionAttack> EndActionAttack(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.ActionAttack>(o);
  }
};

public struct NotifyMove : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static NotifyMove GetRootAsNotifyMove(ByteBuffer _bb) { return GetRootAsNotifyMove(_bb, new NotifyMove()); }
  public static NotifyMove GetRootAsNotifyMove(ByteBuffer _bb, NotifyMove obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public NotifyMove __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float Rotation { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public protocol.world.Vec3? Pos { get { int o = __p.__offset(8); return o != 0 ? (protocol.world.Vec3?)(new protocol.world.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public protocol.world.Vec3? Velocity { get { int o = __p.__offset(10); return o != 0 ? (protocol.world.Vec3?)(new protocol.world.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartNotifyMove(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(0, uuid, 0); }
  public static void AddRotation(FlatBufferBuilder builder, float rotation) { builder.AddFloat(1, rotation, 0.0f); }
  public static void AddPos(FlatBufferBuilder builder, Offset<protocol.world.Vec3> posOffset) { builder.AddStruct(2, posOffset.Value, 0); }
  public static void AddVelocity(FlatBufferBuilder builder, Offset<protocol.world.Vec3> velocityOffset) { builder.AddStruct(3, velocityOffset.Value, 0); }
  public static Offset<protocol.world.NotifyMove> EndNotifyMove(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.NotifyMove>(o);
  }
};

public struct NotifyAttack : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static NotifyAttack GetRootAsNotifyAttack(ByteBuffer _bb) { return GetRootAsNotifyAttack(_bb, new NotifyAttack()); }
  public static NotifyAttack GetRootAsNotifyAttack(ByteBuffer _bb, NotifyAttack obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public NotifyAttack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float Rotation { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<protocol.world.NotifyAttack> CreateNotifyAttack(FlatBufferBuilder builder,
      int uuid = 0,
      float rotation = 0.0f) {
    builder.StartObject(2);
    NotifyAttack.AddRotation(builder, rotation);
    NotifyAttack.AddUuid(builder, uuid);
    return NotifyAttack.EndNotifyAttack(builder);
  }

  public static void StartNotifyAttack(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(0, uuid, 0); }
  public static void AddRotation(FlatBufferBuilder builder, float rotation) { builder.AddFloat(1, rotation, 0.0f); }
  public static Offset<protocol.world.NotifyAttack> EndNotifyAttack(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.NotifyAttack>(o);
  }
};

public struct AppearRemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AppearRemoteCharacter GetRootAsAppearRemoteCharacter(ByteBuffer _bb) { return GetRootAsAppearRemoteCharacter(_bb, new AppearRemoteCharacter()); }
  public static AppearRemoteCharacter GetRootAsAppearRemoteCharacter(ByteBuffer _bb, AppearRemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AppearRemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.world.RemoteCharacter? Character { get { int o = __p.__offset(4); return o != 0 ? (protocol.world.RemoteCharacter?)(new protocol.world.RemoteCharacter()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<protocol.world.AppearRemoteCharacter> CreateAppearRemoteCharacter(FlatBufferBuilder builder,
      Offset<protocol.world.RemoteCharacter> characterOffset = default(Offset<protocol.world.RemoteCharacter>)) {
    builder.StartObject(1);
    AppearRemoteCharacter.AddCharacter(builder, characterOffset);
    return AppearRemoteCharacter.EndAppearRemoteCharacter(builder);
  }

  public static void StartAppearRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacter(FlatBufferBuilder builder, Offset<protocol.world.RemoteCharacter> characterOffset) { builder.AddOffset(0, characterOffset.Value, 0); }
  public static Offset<protocol.world.AppearRemoteCharacter> EndAppearRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.AppearRemoteCharacter>(o);
  }
};

public struct DisappearRemoteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DisappearRemoteCharacter GetRootAsDisappearRemoteCharacter(ByteBuffer _bb) { return GetRootAsDisappearRemoteCharacter(_bb, new DisappearRemoteCharacter()); }
  public static DisappearRemoteCharacter GetRootAsDisappearRemoteCharacter(ByteBuffer _bb, DisappearRemoteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DisappearRemoteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<protocol.world.DisappearRemoteCharacter> CreateDisappearRemoteCharacter(FlatBufferBuilder builder,
      int uuid = 0) {
    builder.StartObject(1);
    DisappearRemoteCharacter.AddUuid(builder, uuid);
    return DisappearRemoteCharacter.EndDisappearRemoteCharacter(builder);
  }

  public static void StartDisappearRemoteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUuid(FlatBufferBuilder builder, int uuid) { builder.AddInt(0, uuid, 0); }
  public static Offset<protocol.world.DisappearRemoteCharacter> EndDisappearRemoteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<protocol.world.DisappearRemoteCharacter>(o);
  }
};

public struct NetMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static NetMessage GetRootAsNetMessage(ByteBuffer _bb) { return GetRootAsNetMessage(_bb, new NetMessage()); }
  public static NetMessage GetRootAsNetMessage(ByteBuffer _bb, NetMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public NetMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MessageT MessageType { get { int o = __p.__offset(4); return o != 0 ? (MessageT)__p.bb.Get(o + __p.bb_pos) : MessageT.NONE; } }
  public TTable? Message<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o) : null; }

  public static Offset<NetMessage> CreateNetMessage(FlatBufferBuilder builder,
      MessageT message_type = MessageT.NONE,
      int messageOffset = 0) {
    builder.StartObject(2);
    NetMessage.AddMessage(builder, messageOffset);
    NetMessage.AddMessageType(builder, message_type);
    return NetMessage.EndNetMessage(builder);
  }

  public static void StartNetMessage(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddMessageType(FlatBufferBuilder builder, MessageT messageType) { builder.AddByte(0, (byte)messageType, 0); }
  public static void AddMessage(FlatBufferBuilder builder, int messageOffset) { builder.AddOffset(1, messageOffset, 0); }
  public static Offset<NetMessage> EndNetMessage(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<NetMessage>(o);
  }
  public static void FinishNetMessageBuffer(FlatBufferBuilder builder, Offset<NetMessage> offset) { builder.Finish(offset.Value); }
};


}
