// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.login
{

using System;
using FlatBuffers;

public struct ReplyCreateCharacterSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyCreateCharacterSuccess GetRootAsReplyCreateCharacterSuccess(ByteBuffer _bb) { return GetRootAsReplyCreateCharacterSuccess(_bb, new ReplyCreateCharacterSuccess()); }
  public static ReplyCreateCharacterSuccess GetRootAsReplyCreateCharacterSuccess(ByteBuffer _bb, ReplyCreateCharacterSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyCreateCharacterSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Character? Character { get { int o = __p.__offset(4); return o != 0 ? (Character?)(new Character()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<ReplyCreateCharacterSuccess> CreateReplyCreateCharacterSuccess(FlatBufferBuilder builder,
      Offset<Character> characterOffset = default(Offset<Character>)) {
    builder.StartObject(1);
    ReplyCreateCharacterSuccess.AddCharacter(builder, characterOffset);
    return ReplyCreateCharacterSuccess.EndReplyCreateCharacterSuccess(builder);
  }

  public static void StartReplyCreateCharacterSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacter(FlatBufferBuilder builder, Offset<Character> characterOffset) { builder.AddOffset(0, characterOffset.Value, 0); }
  public static Offset<ReplyCreateCharacterSuccess> EndReplyCreateCharacterSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReplyCreateCharacterSuccess>(o);
  }
};


}
