// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.login
{

using System;
using FlatBuffers;

public struct ReplyDeleteCharacterFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyDeleteCharacterFailed GetRootAsReplyDeleteCharacterFailed(ByteBuffer _bb) { return GetRootAsReplyDeleteCharacterFailed(_bb, new ReplyDeleteCharacterFailed()); }
  public static ReplyDeleteCharacterFailed GetRootAsReplyDeleteCharacterFailed(ByteBuffer _bb, ReplyDeleteCharacterFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyDeleteCharacterFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<ReplyDeleteCharacterFailed> CreateReplyDeleteCharacterFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    ReplyDeleteCharacterFailed.AddErrorCode(builder, error_code);
    return ReplyDeleteCharacterFailed.EndReplyDeleteCharacterFailed(builder);
  }

  public static void StartReplyDeleteCharacterFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<ReplyDeleteCharacterFailed> EndReplyDeleteCharacterFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReplyDeleteCharacterFailed>(o);
  }
};


}
