// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.login
{

using global::System;
using global::FlatBuffers;

public struct Reply_CreateCharacterFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Reply_CreateCharacterFailed GetRootAsReply_CreateCharacterFailed(ByteBuffer _bb) { return GetRootAsReply_CreateCharacterFailed(_bb, new Reply_CreateCharacterFailed()); }
  public static Reply_CreateCharacterFailed GetRootAsReply_CreateCharacterFailed(ByteBuffer _bb, Reply_CreateCharacterFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Reply_CreateCharacterFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public protocol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (protocol.ErrorCode)__p.bb.GetInt(o + __p.bb_pos) : protocol.ErrorCode.OK; } }

  public static Offset<Reply_CreateCharacterFailed> CreateReply_CreateCharacterFailed(FlatBufferBuilder builder,
      protocol.ErrorCode error_code = protocol.ErrorCode.OK) {
    builder.StartObject(1);
    Reply_CreateCharacterFailed.AddErrorCode(builder, error_code);
    return Reply_CreateCharacterFailed.EndReply_CreateCharacterFailed(builder);
  }

  public static void StartReply_CreateCharacterFailed(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, protocol.ErrorCode errorCode) { builder.AddInt(0, (int)errorCode, 0); }
  public static Offset<Reply_CreateCharacterFailed> EndReply_CreateCharacterFailed(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Reply_CreateCharacterFailed>(o);
  }
};


}
