// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.login
{

using System;
using FlatBuffers;

public struct ReplyJoinSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyJoinSuccess GetRootAsReplyJoinSuccess(ByteBuffer _bb) { return GetRootAsReplyJoinSuccess(_bb, new ReplyJoinSuccess()); }
  public static ReplyJoinSuccess GetRootAsReplyJoinSuccess(ByteBuffer _bb, ReplyJoinSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyJoinSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartReplyJoinSuccess(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<ReplyJoinSuccess> EndReplyJoinSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReplyJoinSuccess>(o);
  }
};


}
