// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.login
{

using global::System;
using global::FlatBuffers;

public struct Reply_CharacterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Reply_CharacterList GetRootAsReply_CharacterList(ByteBuffer _bb) { return GetRootAsReply_CharacterList(_bb, new Reply_CharacterList()); }
  public static Reply_CharacterList GetRootAsReply_CharacterList(ByteBuffer _bb, Reply_CharacterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Reply_CharacterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Character? List(int j) { int o = __p.__offset(4); return o != 0 ? (Character?)(new Character()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Reply_CharacterList> CreateReply_CharacterList(FlatBufferBuilder builder,
      VectorOffset listOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Reply_CharacterList.AddList(builder, listOffset);
    return Reply_CharacterList.EndReply_CharacterList(builder);
  }

  public static void StartReply_CharacterList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddList(FlatBufferBuilder builder, VectorOffset listOffset) { builder.AddOffset(0, listOffset.Value, 0); }
  public static VectorOffset CreateListVector(FlatBufferBuilder builder, Offset<Character>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Reply_CharacterList> EndReply_CharacterList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Reply_CharacterList>(o);
  }
};


}
