// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.login
{

using System;
using FlatBuffers;

public struct ReplyDeleteCharacterSuccess : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ReplyDeleteCharacterSuccess GetRootAsReplyDeleteCharacterSuccess(ByteBuffer _bb) { return GetRootAsReplyDeleteCharacterSuccess(_bb, new ReplyDeleteCharacterSuccess()); }
  public static ReplyDeleteCharacterSuccess GetRootAsReplyDeleteCharacterSuccess(ByteBuffer _bb, ReplyDeleteCharacterSuccess obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ReplyDeleteCharacterSuccess __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<ReplyDeleteCharacterSuccess> CreateReplyDeleteCharacterSuccess(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    ReplyDeleteCharacterSuccess.AddCharacterId(builder, character_id);
    return ReplyDeleteCharacterSuccess.EndReplyDeleteCharacterSuccess(builder);
  }

  public static void StartReplyDeleteCharacterSuccess(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<ReplyDeleteCharacterSuccess> EndReplyDeleteCharacterSuccess(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ReplyDeleteCharacterSuccess>(o);
  }
};


}
