// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.login
{

using System;
using FlatBuffers;

public struct RequestCharacterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestCharacterList GetRootAsRequestCharacterList(ByteBuffer _bb) { return GetRootAsRequestCharacterList(_bb, new RequestCharacterList()); }
  public static RequestCharacterList GetRootAsRequestCharacterList(ByteBuffer _bb, RequestCharacterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestCharacterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRequestCharacterList(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<RequestCharacterList> EndRequestCharacterList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestCharacterList>(o);
  }
};


}
