// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.login
{

using global::System;
using global::FlatBuffers;

public struct Request_CharacterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Request_CharacterList GetRootAsRequest_CharacterList(ByteBuffer _bb) { return GetRootAsRequest_CharacterList(_bb, new Request_CharacterList()); }
  public static Request_CharacterList GetRootAsRequest_CharacterList(ByteBuffer _bb, Request_CharacterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Request_CharacterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRequest_CharacterList(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<Request_CharacterList> EndRequest_CharacterList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Request_CharacterList>(o);
  }
};


}
