// automatically generated by the FlatBuffers compiler, do not modify

namespace protocol.login
{

using System;
using FlatBuffers;

public struct RequestCreateCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RequestCreateCharacter GetRootAsRequestCreateCharacter(ByteBuffer _bb) { return GetRootAsRequestCreateCharacter(_bb, new RequestCreateCharacter()); }
  public static RequestCreateCharacter GetRootAsRequestCreateCharacter(ByteBuffer _bb, RequestCreateCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RequestCreateCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public protocol.ClassType ClassType { get { int o = __p.__offset(6); return o != 0 ? (protocol.ClassType)__p.bb.GetInt(o + __p.bb_pos) : protocol.ClassType.NONE; } }

  public static Offset<RequestCreateCharacter> CreateRequestCreateCharacter(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      protocol.ClassType class_type = protocol.ClassType.NONE) {
    builder.StartObject(2);
    RequestCreateCharacter.AddClassType(builder, class_type);
    RequestCreateCharacter.AddName(builder, nameOffset);
    return RequestCreateCharacter.EndRequestCreateCharacter(builder);
  }

  public static void StartRequestCreateCharacter(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, protocol.ClassType classType) { builder.AddInt(1, (int)classType, 0); }
  public static Offset<RequestCreateCharacter> EndRequestCreateCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RequestCreateCharacter>(o);
  }
};


}
