// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.login
{

using global::System;
using global::FlatBuffers;

public struct Request_DeleteCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Request_DeleteCharacter GetRootAsRequest_DeleteCharacter(ByteBuffer _bb) { return GetRootAsRequest_DeleteCharacter(_bb, new Request_DeleteCharacter()); }
  public static Request_DeleteCharacter GetRootAsRequest_DeleteCharacter(ByteBuffer _bb, Request_DeleteCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Request_DeleteCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Request_DeleteCharacter> CreateRequest_DeleteCharacter(FlatBufferBuilder builder,
      int character_id = 0) {
    builder.StartObject(1);
    Request_DeleteCharacter.AddCharacterId(builder, character_id);
    return Request_DeleteCharacter.EndRequest_DeleteCharacter(builder);
  }

  public static void StartRequest_DeleteCharacter(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, int characterId) { builder.AddInt(0, characterId, 0); }
  public static Offset<Request_DeleteCharacter> EndRequest_DeleteCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Request_DeleteCharacter>(o);
  }
};


}
