// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol.login
{

using global::System;
using global::FlatBuffers;

public struct Request_CreateCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Request_CreateCharacter GetRootAsRequest_CreateCharacter(ByteBuffer _bb) { return GetRootAsRequest_CreateCharacter(_bb, new Request_CreateCharacter()); }
  public static Request_CreateCharacter GetRootAsRequest_CreateCharacter(ByteBuffer _bb, Request_CreateCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Request_CreateCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public protocol.ClassType ClassType { get { int o = __p.__offset(6); return o != 0 ? (protocol.ClassType)__p.bb.GetInt(o + __p.bb_pos) : protocol.ClassType.NONE; } }

  public static Offset<Request_CreateCharacter> CreateRequest_CreateCharacter(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      protocol.ClassType class_type = protocol.ClassType.NONE) {
    builder.StartObject(2);
    Request_CreateCharacter.AddClassType(builder, class_type);
    Request_CreateCharacter.AddName(builder, nameOffset);
    return Request_CreateCharacter.EndRequest_CreateCharacter(builder);
  }

  public static void StartRequest_CreateCharacter(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddClassType(FlatBufferBuilder builder, protocol.ClassType classType) { builder.AddInt(1, (int)classType, 0); }
  public static Offset<Request_CreateCharacter> EndRequest_CreateCharacter(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Request_CreateCharacter>(o);
  }
};


}
